name: Comprobar que docker compose funciona
on: [push,pull_request]
jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Construye el cluster
        run: docker-compose up -d
      - name: Testea el cluster
        run: wget http://localhost:31415/status || exit 1
